"""Parse the original DRACULA.TXT (80-byte random-access records) into a World.

Format summary (full details in docs/txt-format.md):

* Flat array of 80-byte records; record k at byte offset k*80.
* Record 0 holds 5 uint16 section-boundary indices:
  [room_text_start, message_start, object_start, cont_start, total].
* Records 1..100          = room exit vectors (room r at record r+1; 7 uint16 dirs).
* Records 101..200        = room description first lines  (room r at record 101+r).
* Records 201..700        = messages / responses.
* Records 701..800        = objects (text[0:76] + attr@76 + location@78).
* Records 801..1288       = shared continuation/overflow line pool.
* Text records: bytes[0:78] text (space/null padded) + bytes[78:80] next-line
  pointer as a 1-based record number (0 = end). my_index = pointer - 1.
"""
from __future__ import annotations

import json
import struct
from pathlib import Path

from .model import GameObject, Room, World

REC = 80
ENCODING = "cp437"

# Default location of the original data file within the project.
DEFAULT_TXT = Path(__file__).resolve().parents[2] / "original" / "DRACULA.TXT"

# The self-contained runtime world data (UTF-8 JSON, generated by tools/build_world.py).
DEFAULT_WORLD = Path(__file__).resolve().parent / "world.json"

# Curated spelling corrections to the original Dutch text (see corrections_nl.json).
_CORRECTIONS_PATH = Path(__file__).resolve().parent / "corrections_nl.json"


def _load_corrections() -> dict[str, dict[int, list[tuple[str, str]]]]:
    """Parse corrections_nl.json into ``{'messages': {id: subs}, 'rooms': {...},
    'objects': {...}}`` with int keys; each ``subs`` is a list of ``(wrong, right)``."""
    empty = {"messages": {}, "rooms": {}, "objects": {}}
    try:
        data = json.loads(_CORRECTIONS_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return empty
    out: dict[str, dict[int, list[tuple[str, str]]]] = {k: {} for k in empty}
    for section in out:
        for key, subs in data.get(section, {}).items():
            try:
                out[section][int(key)] = [(a, b) for a, b in subs]
            except (ValueError, TypeError):
                continue
    return out


def _apply_subs(text: str, subs: list[tuple[str, str]]) -> str:
    for old, new in subs:
        text = text.replace(old, new)
    return text


def apply_corrections(world: World) -> None:
    """Apply the curated Dutch spelling corrections to the *displayed* text.

    Only the shown text is touched — ``world.messages``, ``room.lines`` and
    ``object.name``. ``object.raw_text`` is left as-is. ``world.json`` itself stores the
    UNCORRECTED base text and corrections are applied only to the displayed text at load
    time, so the original is always recoverable verbatim (load with ``corrections=False``).
    This is a deliberate, documented modernisation of the 1982 original (the
    'Gemoderniseerde versie'), not a translation — it runs before any
    :class:`~engine.i18n.Translator`, so a translation overlays a corrected base.
    """
    corr = _load_corrections()
    for mid, subs in corr["messages"].items():
        lines = world.messages.get(mid)
        if lines:
            world.messages[mid] = [_apply_subs(line, subs) for line in lines]
    for rid, subs in corr["rooms"].items():
        room = world.rooms.get(rid)
        if room:
            room.lines = [_apply_subs(line, subs) for line in room.lines]
    for oid, subs in corr["objects"].items():
        obj = world.objects.get(oid)
        if obj:
            obj.name = _apply_subs(obj.name, subs)


def _decode(b: bytes) -> str:
    return b.decode(ENCODING)


class RecordFile:
    """Low-level accessor over the 80-byte record array."""

    def __init__(self, data: bytes):
        if len(data) < REC:
            raise ValueError("DRACULA.TXT too small")
        self.data = data
        self.n_records = len(data) // REC
        self.header = list(struct.unpack_from("<5H", data, 0))

    def record(self, i: int) -> bytes:
        return self.data[i * REC:(i + 1) * REC]

    def words(self, record_index: int, count: int, word_offset: int = 0) -> list[int]:
        base = record_index * REC + word_offset * 2
        return list(struct.unpack_from("<%dH" % count, self.data, base))

    def text_field(self, i: int, width: int = 78) -> str:
        return _decode(self.record(i)[:width]).rstrip(" \x00")

    def next_pointer(self, i: int) -> int:
        return struct.unpack_from("<H", self.record(i), 78)[0]

    def assemble(self, start_index: int) -> list[str]:
        """Collect a text record plus its continuation chain (1-based pointers)."""
        lines = [self.text_field(start_index)]
        nxt = self.next_pointer(start_index)
        seen = {start_index}
        while nxt != 0:
            idx = nxt - 1
            if idx < 0 or idx >= self.n_records or idx in seen:
                break
            seen.add(idx)
            lines.append(self.text_field(idx))
            nxt = self.next_pointer(idx)
        return lines


def parse_object_text(text: str) -> tuple[list[str], str]:
    """Split '/LANT/BRAN/LAMPkleine brandende lantaren' into tokens + name.

    Tokens are 4-char groups, each introduced by '/'. The remainder is the name.
    Records with no leading '/' have no parser tokens (scenery / state variants).
    """
    tokens: list[str] = []
    s = text
    while s.startswith("/") and len(s) >= 5:
        tokens.append(s[1:5].strip())
        s = s[5:]
    return tokens, s


def load(data: bytes) -> World:
    rf = RecordFile(data)
    room_text_start, message_start, object_start, cont_start, total = rf.header

    n_rooms = message_start - room_text_start          # 100
    n_messages = object_start - message_start          # 500
    n_objects = cont_start - object_start              # 100

    rooms: dict[int, Room] = {}
    for r in range(n_rooms):
        exits = rf.words(r + 1, 7)                     # room r exits at record r+1
        lines = rf.assemble(room_text_start + r)
        rooms[r] = Room(id=r, exits=exits, lines=lines,
                        first_record=room_text_start + r)

    messages: dict[int, list[str]] = {}
    for m in range(n_messages):
        messages[m] = rf.assemble(message_start + m)

    objects: dict[int, GameObject] = {}
    for o in range(n_objects):
        rec = rf.record(object_start + o)
        raw_text = _decode(rec[:76]).rstrip(" \x00")
        attr = struct.unpack_from("<H", rec, 76)[0]
        loc = struct.unpack_from("<H", rec, 78)[0]
        tokens, name = parse_object_text(raw_text)
        objects[o] = GameObject(id=o, tokens=tokens, name=name,
                                attribute=attr, location=loc, raw_text=raw_text)

    return World(rooms=rooms, messages=messages, objects=objects,
                 header=rf.header, raw=data)


def load_json(path: str | Path | None = None, *, translator=None,
              corrections: bool = True) -> World:
    """Load the world from engine/data/world.json (the self-contained, UTF-8 asset).

    The JSON holds the ORIGINAL, uncorrected text. ``corrections`` (default on) applies
    the curated spelling fixes in code; a ``translator`` overlays a translation. This is
    the runtime path — it never reads the original DRACULA.TXT.
    """
    p = Path(path) if path is not None else DEFAULT_WORLD
    world = World.from_dict(json.loads(p.read_text(encoding="utf-8")))
    if corrections:
        apply_corrections(world)
    if translator is not None:
        translator.apply(world)
    return world


def load_file(path: str | Path | None = None, *, translator=None,
              corrections: bool = True) -> World:
    """Load the world. With no ``path`` (the normal case) this reads the bundled
    ``world.json``; an explicit ``path`` is treated as a legacy original ``DRACULA.TXT``
    and parsed from bytes (used by tools/tests that still work from the raw file).

    ``translator`` is an optional :class:`engine.i18n.Translator`; with none (or a
    default Dutch translator) the result is the original Dutch. ``corrections`` applies
    the curated spelling fixes to the displayed text (the 'Gemoderniseerde' build).
    """
    if path is None:
        return load_json(translator=translator, corrections=corrections)
    world = load(Path(path).read_bytes())
    if corrections:
        apply_corrections(world)
    if translator is not None:
        translator.apply(world)
    return world
